[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mask-designer"
authors = [{name = "Nicolas BÃ¤hler", email = "nicolas.bahler@epfl.ch"}]
dynamic = ["version", "description"]
